### ISSUE TITLE
errror protected

### ISSUE THREAD

**Issue by blanksixs** [PXgamer/youtube-dl-php#1]
i try but the error show like this ser

Fatal error: Call to protected YDP::__construct() from invalid context in C:\wamp64\www\gr\index.php on line 3

**Comment by owenvoke** [comment]
Should be fixed. Could you try now.
ecdb141a42ed6b8354a5af0b74a11120ce4f0b91

**Comment by blanksixs** [comment]
nice, it's work, but when i klik the download link this link just stream the video ser.
and can you give the list and content and the search engine from youtube ser :D

![assss](https://cloud.githubusercontent.com/assets/22504254/18931715/8b66bf48-85f7-11e6-9d27-15fa42ed044f.JPG)

**Comment by owenvoke** [comment]
Currently I'm working on implementing a proper download system (as currently it just uses the HTML5 `download` tag.

So, if HTML5 isn't supported fully, this may not work. Bear in mind, I've only tested on Chrome for now.

Once that download is done, then should be good to go.

Cheers for having an interest in this.

**Comment by ScribeOfGoD** [comment]
Fixed?
