### ISSUE TITLE
Add a new download method for non-HTML5 browsers

### ISSUE THREAD

**Issue by owenvoke** [PXgamer/youtube-dl-php#2]
Add a new download method as a fallback for non-HTML5 capable browsers.

Currently it just uses the HTML5 `download` attribute on the `a` tags.

Need to add a function to the class that detects if there is a download (i.e. a parameter `$_REQUEST['dl']`) requested.

**Comment by xRahul** [comment]
I'll take this one!

**Comment by owenvoke** [comment]
@xRahul sure. 😄

**Comment by xRahul** [comment]
Hey @PXgamer 
I've been looking into different methods for doing this like using download.js, or using iframe.. But they aren't any good like the method we have currently.
download.js first downloads entire file via ajax in the browser, and then gives the output, somewhat like how mega's download works.
iframe won't download the video file if there's no `Content-Disposition: attachment` header from server side.
Do you have some method in mind?

**Comment by owenvoke** [comment]
Hi @xRahul I was thinking about a new function that can be passed an extra 2 parameters.

| Name | Type |
| --- | --- |
| $download | Boolean |
| $type | String |

Where type is the id representing the quality (e.g. `720mp4`).

Then you could call this from a web page like:

``` php
<?php
include './ydp.class.php';
$ydp = new YDP ('id');
(isset ($_REQUEST['dl']) && isset ($_REQUEST['type'])) ? $ydp->download($_REQUEST['dl'], $_REQUEST['type']) : $ydp->display();
```

**Comment by xRahul** [comment]
There are 2 ways to implement that-
1. You can download the file on the server, and then trigger download for the client after it is successfully downloaded via php. It could take some time for the file to be downloaded first on the server.
2. Redirect user to the download url for the file, which will most likely open the video in a browser tab, but it won't require server side download.

There are ways to download file via ajax, but the youtube url has cross-origin requests disabled.
Let me know if you have one of them in mind

**Comment by owenvoke** [comment]
Leaving this for now as it'd add unnecessary code to the collection.

**Comment by xRahul** [comment]
Sure.. if there's anything else, let me know!
