### ISSUE TITLE
Working copy of index.php

### ISSUE THREAD

**Issue by MacsInSpace** [PXgamer/youtube-dl-php#3]
Do you have a working copy of index.php from https://youtube-dl-php.pxgamer.xyz/ available?
I'm no php developer and can't work out how to create the form correctly. 
It just keeps giving me the submitted page at the first.

**Comment by owenvoke** [comment]
Hi, I was actually planning on redoing this as it's not as efficient as it can be.

The `index.php` I used is available here.
https://gist.github.com/PXgamer/e05f4890526820666c4960f0e633ec86

**Comment by MacsInSpace** [comment]
Thanks!
I'm a network admin for a few Australian (Vic) government schools and my staff are downloading various "youtube downloader" apps and browser extensions - all with added spyware and browser hijackers of course.
Rather than block it, I just want to mitigate the risk of them doing it at home and host our own internal helper.
I look forward to your updates!
Craig

**Comment by owenvoke** [comment]
Ok, I updated this in commit bfcdd9264c77f9af436b0461f45c989d25663725 which contains quite a few changes.

You can now point a web server to the `public/` directory. 😄
