### ISSUE TITLE
stream and downloading issues

### ISSUE THREAD

**Issue by jhaylee2016** [PXgamer/youtube-dl-php#6]
i just check now and its 403 denied or forbidden...can you fix it please...

**Comment by owenvoke** [comment]
I've tested multiple videos and can't find a problem.

I know that this has happened before occasionally when it is a monetised, or unlisted video.

Could you provide some example video IDs that this is occurring on?

**Comment by jhaylee2016** [comment]
Thanks for the response @pxgamer..try vevo videos...all generated dowbload links are denied

**Comment by owenvoke** [comment]
Checked and I see what you mean, I'm pretty sure this is part of YouTube's protection for monetised videos.

I'll look into ways of bypassing this, but I guess it may be against their ToS.
